version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: teste
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: .
    container_name: nest-backend
    ports:
      - "3498:3498"
    environment:
      SQL_SERVER_HOST: postgres
      SQL_SERVER_PORT: 5432
      SQL_SERVER_USER: postgres
      SQL_SERVER_PASSWORD: postgres
      SQL_SERVER_DATABASE: teste
      TYPEORM_APPLY_MIGRATION_ON_STARTUP: 'Y'
      JWT_SECRET: 'GqAUNp-hWjIJctiM0s4cDC33msGVmCAl2wCoueCeEvxFLKa2gE30VEfjNcSP9jLsBg3ei-svhJpOZ2TUWXuZTw'
      APP_URL: 'http://localhost'
      NODE_ENV: production
      PORT: 3498
    depends_on:
      postgres:
        condition: service_healthy

  test:
    build: .
    container_name: nest-tests
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SQL_SERVER_HOST: postgres
      SQL_SERVER_PORT: 5432
      SQL_SERVER_USER: postgres
      SQL_SERVER_PASSWORD: postgres
      SQL_SERVER_DATABASE: teste
      NODE_ENV: test
    command: yarn test

volumes:
  postgres_data:

  
