version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - "3498:3498"
    env_file:
      - .env
    depends_on:
      - database
    command: [ "npm", "run", "start" ]

  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongPassword123!"
      MSSQL_PID: "Express"
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
